# Generated by Django 3.1.3 on 2020-12-07 09:07

from django.db import migrations, models
import room.models


class Migration(migrations.Migration):

    dependencies = [
        ('room', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_status', models.CharField(choices=[('HO', 'Host'), ('MO', 'Moderator'), ('GU', 'Guest')], default='GU', max_length=2)),
            ],
        ),
        migrations.AlterField(
            model_name='room',
            name='code',
            field=models.CharField(default=room.models.generate_unique_code, max_length=8, unique=True),
        ),
    ]
