# Generated by Django 3.1.3 on 2020-12-07 09:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('room', '0002_auto_20201207_1107'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='session_key',
            field=models.CharField(default=None, max_length=40, unique=True),
        ),
    ]
