# Generated by Django 3.1.3 on 2020-12-07 12:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('room', '0003_user_session_key'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='id_room',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='room.room'),
        ),
    ]
