# Generated by Django 3.1.3 on 2020-12-07 12:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('room', '0005_auto_20201207_1437'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user',
            old_name='id_room',
            new_name='room',
        ),
    ]
