# Generated by Django 3.1.3 on 2020-12-07 12:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('room', '0006_auto_20201207_1438'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='room',
        ),
    ]
