# Generated by Django 3.1.3 on 2020-12-07 13:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('room', '0009_auto_20201207_1445'),
    ]

    operations = [
        migrations.AlterField(
            model_name='room',
            name='guest_can_seek',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='room',
            name='guest_can_use_chat',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='room',
            name='moder_can_add',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='room',
            name='moder_can_move',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='room',
            name='moder_can_playpause',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='room',
            name='moder_can_remove',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='room',
            name='moder_can_seek',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='room',
            name='moder_can_skip',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='room',
            name='moder_can_use_chat',
            field=models.BooleanField(default=True),
        ),
    ]
