# Generated by Django 3.1.3 on 2020-12-19 13:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('room', '0010_auto_20201207_1550'),
    ]

    operations = [
        migrations.DeleteModel(
            name='User',
        ),
    ]
